"""Project workspace: real files on disk + real git commits per agent.

Fix for FIXES.md §4 — "FORGE agents must actually write files."
Each project gets its own directory under ./projects/<id>/repo with a git repo.
Agents create branches and commit real files parsed from their LLM output.
"""
from __future__ import annotations
import logging
import os
import re
import subprocess
from pathlib import Path
from typing import Iterable

log = logging.getLogger("ariya.workspace")

ROOT = Path(os.getenv("ARIYA_PROJECTS_DIR", "./projects")).resolve()

# Match agent file blocks. Two formats accepted:
#   FILE: path/to/file.ts
#   ```lang
#   ...code...
#   ```
# Or a fenced block prefixed with `// FILE: path` on the first line inside.
_FILE_BLOCK = re.compile(
    r"(?:FILE:\s*([^\n`]+)\s*\n)?```(?:[a-zA-Z0-9_+-]*)\n(?:\s*(?://|#)\s*FILE:\s*([^\n]+)\n)?(.*?)```",
    re.DOTALL,
)


def parse_files_from_text(text: str) -> list[tuple[str, str]]:
    """Pull (path, content) pairs out of agent output."""
    files: list[tuple[str, str]] = []
    for match in _FILE_BLOCK.finditer(text):
        path = (match.group(1) or match.group(2) or "").strip()
        body = match.group(3)
        if not path:
            continue
        # sanitize — no traversal, no absolute paths
        if ".." in path or path.startswith(("/", "\\")) or ":" in path:
            log.warning("rejected unsafe path: %s", path)
            continue
        files.append((path, body))
    return files


def _git(cwd: Path, *args: str) -> str:
    res = subprocess.run(
        ["git", *args],
        cwd=str(cwd),
        capture_output=True,
        text=True,
        env={**os.environ, "GIT_TERMINAL_PROMPT": "0"},
    )
    if res.returncode != 0:
        log.warning("git %s failed: %s", " ".join(args), res.stderr.strip())
    return res.stdout.strip()


class ProjectWorkspace:
    def __init__(self, project_id: str):
        self.project_id = project_id
        self.path = ROOT / project_id / "repo"
        self.path.mkdir(parents=True, exist_ok=True)
        if not (self.path / ".git").exists():
            _git(self.path, "init", "-q", "-b", "main")
            _git(self.path, "config", "user.email", "ariya@local")
            _git(self.path, "config", "user.name", "ARIYA")
            (self.path / "README.md").write_text(
                f"# Project {project_id}\n\nGenerated by ARIYA.\n", encoding="utf-8"
            )
            _git(self.path, "add", "README.md")
            _git(self.path, "commit", "-q", "-m", "init")

    def branch(self, name: str) -> None:
        existing = _git(self.path, "branch", "--list", name)
        if existing:
            _git(self.path, "checkout", "-q", name)
        else:
            _git(self.path, "checkout", "-q", "-b", name)

    def commit_files(self, files: Iterable[tuple[str, str]], message: str, agent_id: str) -> str:
        wrote = 0
        for path, body in files:
            target = self.path / path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(body, encoding="utf-8")
            wrote += 1
        if wrote == 0:
            return ""
        _git(self.path, "add", "-A")
        _git(self.path, "commit", "-q",
             "--author", f"{agent_id} <{agent_id.lower()}@ariya>",
             "-m", message)
        return _git(self.path, "rev-parse", "HEAD")

    def list_files(self) -> list[str]:
        out = _git(self.path, "ls-files")
        return [l for l in out.splitlines() if l]

    def diff(self, base: str = "main") -> str:
        return _git(self.path, "diff", base)
